name: Schedule

on:
   schedule:
    - cron: "*/1 * * * *"
   release:
    types: [created]
    workflow_dispatch: # Put here!!
  
jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Script executed!
